### ISSUE TITLE
Oct meetup picture overflows on to August meetup article

### ISSUE THREAD

**Issue by shrayasr** [Chennaipy/website#39] opened 2014-12-22 02:49 UTC
**Screenshot of the issue**:
![screenshot 2014-12-22 08 05 41](https://cloud.githubusercontent.com/assets/240368/5520721/77f6e120-89b1-11e4-8581-a2f0526a07cd.png)

There seems to be some problem with images overflowing from one article into another. A `pure.css` bug, perhaps?

**Comment by astronomersiva** [comment] 2015-01-06 12:50
I think the problem is with the float: right styling that has been given to that image. I removed that and it solves this overflow issue.

![october](https://cloud.githubusercontent.com/assets/7725225/5628659/4faf50be-95d0-11e4-9f95-ead65847abd3.png)

Also, in the November meetup section, the meta details(in misc. Mon 01 December 2014) is in the same line as the picture. This is because the image's closing tag isn't present and there is a </p> tag in its place instead.

**Comment by astronomersiva** [comment] 2015-01-06 12:52
I think the problem is with the float: right styling that has been given to that image. I removed that and it solves this overflow issue.

![october](https://cloud.githubusercontent.com/assets/7725225/5628659/4faf50be-95d0-11e4-9f95-ead65847abd3.png)

Also, in the November meetup section, the meta details(in misc. Mon 01 December 2014) is in the same line as the picture. This is because the image's closing tag isn't present and there is a `</p>` tag in its place instead.

**Comment by shrayasr** [comment] 2015-01-06 13:08
I see, If this is an issue with our stylesheet or the theme's?

**Comment by astronomersiva** [comment] 2015-01-06 13:31
I just went through a sample blog that looks highly similar to ChennaiPy's website in the Pure CSS website. When I added a picture there, I got the same overflow problem. So this is an issue with the theme. Here, the section block's contents are given a display: block attribute that is causing this overflow issue. A way to bypass this will be to remove that inline CSS I had mentioned earlier as the other pics in the website are also displayed in a new line instead of being displayed in the same line.

**Comment by shrayasr** [comment] 2015-01-06 15:58
Awesome :+1:

So you could do 2 things: 

1. Post an issue on the Pure CSS if it hasn't been fixed in the latest releases
2. Override the default style in our theme

**Comment by astronomersiva** [comment] 2015-01-06 16:18
I shall give a PR and fix this in our theme along with the November meetup mistake too.

**Comment by shrayasr** [comment] 2015-01-06 16:20
:+1: Thanks :)

**Comment by bravegnu** [comment] 2015-01-07 15:40
A better way to handle this issue is to specify summary meta data for all articles. So that pelican does not cut us out at the wrong spot.

**Comment by bravegnu** [comment] 2015-01-07 15:55
More info on summary at http://docs.getpelican.com/en/latest/content.html#file-metadata

**Comment by bravegnu** [comment] 2015-01-08 16:09
This is how the page looks with the above change.

![screenshot](https://cloud.githubusercontent.com/assets/1171852/5665441/856e6bb8-977e-11e4-8c06-27956b694063.png)

**Comment by shrayasr** [comment] 2015-01-08 16:12
LGTM. Merging!

**Closed** 2015-01-08 16:12 UTC
Labels: bug
